name: yggdrasilleon
base: core22
version: '1.0.0'
summary: "Yggdrasilleon - Interactive Graph Algorithm Visualizer"
description: |
  Yggdrasilleon is a Qt-based application for visualizing graph algorithms
  such as Dijkstra, Bellman-Ford, and Floyd-Warshall. It includes step-by-step
  animations, cycle detection, and an integrated man-page style help system.

grade: stable   # use "devel" if still testing
confinement: strict

apps:
  yggdrasilleon:
    command: usr/bin/Yggdrasilleon
    desktop: usr/share/applications/Yggdrasilleon.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - home

parts:
  yggdrasilleon:
    plugin: cmake
    source: .
    build-packages:
      - g++
      - cmake
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev
      - qt5-qmake
      - libgl1-mesa-dev
      - libglu1-mesa-dev
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5core5a
      - libqt5printsupport5
      - libqt5svg5
      - libgl1
      - libglu1-mesa
    organize:
      usr/local/bin/Yggdrasilleon: usr/bin/Yggdrasilleon
      usr/local/share/applications/Yggdrasilleon.desktop: usr/share/applications/Yggdrasilleon.desktop
      usr/local/share/icons/hicolor/256x256/apps/Yggdrasilleon.png: usr/share/icons/hicolor/256x256/apps/Yggdrasilleon.png
